package pi

import (
	"context"
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/entireio/cli/cmd/entire/cli/agent"
	"github.com/entireio/cli/cmd/entire/cli/paths"
)

// Compile-time interface assertions
var (
	_ agent.HookSupport   = (*PiAgent)(nil)
	_ agent.HookFreshness = (*PiAgent)(nil)
)

//go:embed entire_extension.ts
var extensionTemplate string

const (
	// extensionDirName is the directory pi auto-discovers project-local
	// extensions from.
	extensionDirName = ".pi/extensions/entire"

	// extensionFileName is the file pi loads from extensionDirName.
	extensionFileName = "index.ts"

	// entireMarker identifies the file as Entire-owned. Substring of the
	// auto-generated header so AreHooksInstalled can verify ownership by
	// content (and so it survives the ENTIRE_CMD placeholder substitution).
	entireMarker = "Auto-generated by `entire enable --agent pi`"

	// entireCmdPlaceholder is replaced at install time with either `entire`
	// (production) or a `go run …` path (local-dev).
	entireCmdPlaceholder = "__ENTIRE_CMD__"

	// piNestedEnvVar marks a Pi process so any Pi it spawns can tell it is nested
	// and skip forwarding session lifecycle. Set and read only by the embedded
	// extension — Entire's hook subprocesses inherit it, so no Go code may treat it
	// as a skip signal.
	piNestedEnvVar = "ENTIRE_PI_NESTED"
)

func extensionPath(ctx context.Context) (string, error) {
	root, err := paths.WorktreeRoot(ctx)
	if err != nil {
		// Fall back to CWD for tests run outside a git repo.
		//nolint:forbidigo // explicit fallback when WorktreeRoot fails
		root, err = os.Getwd()
		if err != nil {
			return "", fmt.Errorf("resolve repo root: %w", err)
		}
	}
	return filepath.Join(root, extensionDirName, extensionFileName), nil
}

func renderExtension(localDev bool) string {
	var cmd string
	if localDev {
		cmd = agent.LocalDevHookScript
	} else {
		cmd = "entire"
	}
	return strings.ReplaceAll(extensionTemplate, entireCmdPlaceholder, cmd)
}

// InstallHooks writes the Entire pi extension to .pi/extensions/entire/index.ts.
// Returns 1 if the extension was written, 0 if already up-to-date (idempotent).
// If the file exists but content differs (e.g., localDev vs production), it is
// rewritten as long as it is recognisable as Entire-owned (contains the
// marker). A foreign file at the same path is left untouched unless force is
// true — this protects user-authored extensions that happen to live at
// .pi/extensions/entire/index.ts.
func (a *PiAgent) InstallHooks(ctx context.Context, localDev bool, force bool) (int, error) {
	path, err := extensionPath(ctx)
	if err != nil {
		return 0, err
	}
	content := renderExtension(localDev)

	if !force {
		//nolint:gosec // path constructed from validated repo root
		existing, readErr := os.ReadFile(path)
		switch {
		case readErr == nil && string(existing) == content:
			return 0, nil // already up-to-date
		case readErr == nil && !strings.Contains(string(existing), entireMarker):
			return 0, fmt.Errorf("refusing to overwrite foreign file at %s; remove it or pass --force", path)
		}
	}

	//nolint:gosec // G301: pi reads the directory; standard 0755 permissions
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return 0, fmt.Errorf("create extension dir: %w", err)
	}
	//nolint:gosec // G306: pi reads the file; standard 0644 permissions
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return 0, fmt.Errorf("write extension: %w", err)
	}
	return 1, nil
}

// UninstallHooks removes the entire pi extension directory (if present).
func (a *PiAgent) UninstallHooks(ctx context.Context) error {
	path, err := extensionPath(ctx)
	if err != nil {
		return err
	}
	dir := filepath.Dir(path)
	if err := os.RemoveAll(dir); err != nil {
		return fmt.Errorf("remove pi extension dir: %w", err)
	}
	return nil
}

// AreHooksInstalled returns true when the extension file exists and is
// recognisable as Entire-owned (contains the marker string).
func (a *PiAgent) AreHooksInstalled(ctx context.Context) bool {
	path, err := extensionPath(ctx)
	if err != nil {
		return false
	}
	//nolint:gosec // path from validated repo root
	data, err := os.ReadFile(path)
	if err != nil {
		return false
	}
	return strings.Contains(string(data), entireMarker)
}

// CheckHookConfig reports whether the installed extension matches what
// InstallHooks would write today. Read-only diagnostic for `entire status` and
// `entire doctor`.
//
// This matters more for pi than for agents that configure hooks in a local
// settings file: repos commonly commit .pi/extensions/entire/index.ts so every
// clone gets checkpointing without each person enabling it by hand. A committed
// extension goes stale as the template evolves, and AreHooksInstalled keeps
// returning true because the marker is still there — while the extension's own
// fireHook swallows every error by design, so broken hooks are silent. Without
// this check a stale committed extension reads as healthy forever.
func (a *PiAgent) CheckHookConfig(ctx context.Context) agent.HookConfigState {
	path, err := extensionPath(ctx)
	if err != nil {
		return agent.HooksAbsent
	}
	return agent.GeneratedHookFileState(path, entireMarker, renderExtension(false), renderExtension(true))
}
